# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend # Path to frontend Dockerfile + code
      dockerfile: Dockerfile
    image: tv-show-app # Optional: name the built image
    ports:
      - "3000:80" # Map host port 3000 to container port 80
    depends_on:
      - api-backend # Ensure backend starts first (optional but good practice)
    networks:
      - app-network

  api-backend:
    build:
      context: ./api # Path to backend Dockerfile + code
      dockerfile: Dockerfile
    image: fastapi-backend-app # Optional: name the built image
    environment:
      # Pass necessary environment variables to the backend
      - AWS_REGION=${AWS_REGION} # Reads from your host env or .env file
      - DYNAMODB_TABLE_NAME=${DYNAMODB_TABLE}
    networks:
      - app-network
    # Note: Backend doesn't need 'ports' exposed unless you want direct host access

networks:
  app-network:
    driver: bridge